# Generated by Django 3.0.5 on 2020-04-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcount',
            old_name='test_count',
            new_name='tested',
        ),
    ]
